version: '3'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full WordPress project
      - ./config/mu-plugins/mailhog.php:/var/www/html/wp-content/mu-plugins/mailhog.php # Force WordPress to send emails via mailhog
      #- ./wp-source/plugin-name/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./wp-source/theme-name/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG}"
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG}"
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  mailhog:
    image: mailhog/mailhog # https://hub.docker.com/r/mailhog/mailhog/
    ports:
      - ${IP}:1025:1025 # smtp server
      - ${IP}:8025:8025 # web ui

  composer2:
    image: composer:latest # https://hub.docker.com/_/composer
    user: 1000:1000
    working_dir: /var/www/html
    volumes:
      - ./var/www/html
      #- ./wp-source/plugin-name/:/var/www/html/wp-content/plugins/plugin-name # Plugin executing composer folder
      #- ./wp-source/theme-name/:/var/www/html/wp-content/themes/theme-name # Theme executing composer folder
    depends_on:
      - wp

  node15:
    image: node:15 # https://hub.docker.com/_/node
    user: 1000:1000
    working_dir: /var/www/html
    volumes:
      - ./var/www/html
      #- ./wp-source/plugin-name/:/var/www/html/wp-content/plugins/plugin-name # Plugin executing npm folder
      #- ./wp-source/theme-name/:/var/www/html/wp-content/themes/theme-name # Theme executing npm folder
    depends_on:
      - wp


volumes:
  db_data:
